//! Bulk operations
//!
//! Generated by backbone-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod notification_bulk;
pub mod notification_preference_bulk;

pub use notification_bulk::NotificationBulkService;
pub use notification_preference_bulk::NotificationPreferenceBulkService;

// <<< CUSTOM
// END CUSTOM
