//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod notification_bulk;
pub mod notification_template_bulk;

pub use notification_bulk::NotificationBulkService;
pub use notification_template_bulk::NotificationTemplateBulkService;

// <<< CUSTOM
// END CUSTOM
