//! Notification DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Notification;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::NotificationChannel;
use crate::domain::entity::NotificationPriority;
use crate::domain::entity::NotificationStatus;
use crate::domain::entity::NotificationType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Notification
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateNotificationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    pub notification_type: NotificationType,
    pub channel: NotificationChannel,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action_type: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reference_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reference_id: Option<Uuid>,
    pub status: NotificationStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sent_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delivered_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub read_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failed_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub retry_count: i32,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    pub priority: NotificationPriority,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_actionable: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub action_taken: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action_taken_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_dismissed: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dismissed_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Notification
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateNotificationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    pub notification_type: NotificationType,
    pub channel: NotificationChannel,
    #[cfg_attr(feature = "validation", validate(length(max = 255)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "validation", validate(length(max = 2000)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 500)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action_type: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 50)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reference_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reference_id: Option<Uuid>,
    pub status: NotificationStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sent_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub delivered_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub read_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failed_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(range(max = 255)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub retry_count: i32,
    #[cfg_attr(feature = "validation", validate(range(max = 100)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    pub priority: NotificationPriority,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_actionable: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub action_taken: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action_taken_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_dismissed: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dismissed_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Notification
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchNotificationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notification_type: Option<NotificationType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel: Option<NotificationChannel>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action_url: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action_type: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reference_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reference_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<NotificationStatus>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sent_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivered_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub read_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failed_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retry_count: Option<i32>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub priority: Option<NotificationPriority>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_actionable: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action_taken: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action_taken_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_dismissed: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dismissed_at: Option<DateTime<Utc>>,
}

impl PatchNotificationDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.user_id.is_some() || self.notification_type.is_some() || self.channel.is_some() || self.title.is_some() || self.body.is_some() || self.image_url.is_some() || self.action_url.is_some() || self.action_type.is_some() || self.reference_type.is_some() || self.reference_id.is_some() || self.status.is_some() || self.scheduled_at.is_some() || self.sent_at.is_some() || self.delivered_at.is_some() || self.read_at.is_some() || self.failed_at.is_some() || self.failure_reason.is_some() || self.retry_count.is_some() || self.external_id.is_some() || self.priority.is_some() || self.is_actionable.is_some() || self.action_taken.is_some() || self.action_taken_at.is_some() || self.is_dismissed.is_some() || self.dismissed_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Notification entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct NotificationResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    pub notification_type: NotificationType,
    pub channel: NotificationChannel,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action_url: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reference_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reference_id: Option<Uuid>,
    pub status: NotificationStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub sent_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delivered_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub read_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failed_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub failure_reason: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub retry_count: i32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
    pub priority: NotificationPriority,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_actionable: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub action_taken: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action_taken_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_dismissed: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dismissed_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Notification entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct NotificationListResponseDto {
    /// List of items
    pub items: Vec<NotificationResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl NotificationListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<NotificationResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct NotificationSummaryDto {
    pub id: Uuid,
    pub user_id: Uuid,
    pub notification_type: NotificationType,
    pub channel: NotificationChannel,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Notification> for NotificationResponseDto {
    fn from(entity: Notification) -> Self {
        Self {
            id: entity.id,
            user_id: entity.user_id,
            notification_type: entity.notification_type,
            channel: entity.channel,
            title: entity.title,
            body: entity.body,
            image_url: entity.image_url,
            action_url: entity.action_url,
            action_type: entity.action_type,
            reference_type: entity.reference_type,
            reference_id: entity.reference_id,
            status: entity.status,
            scheduled_at: entity.scheduled_at,
            sent_at: entity.sent_at,
            delivered_at: entity.delivered_at,
            read_at: entity.read_at,
            failed_at: entity.failed_at,
            failure_reason: entity.failure_reason,
            retry_count: entity.retry_count,
            external_id: entity.external_id,
            priority: entity.priority,
            is_actionable: entity.is_actionable,
            action_taken: entity.action_taken,
            action_taken_at: entity.action_taken_at,
            is_dismissed: entity.is_dismissed,
            dismissed_at: entity.dismissed_at,
            metadata: entity.metadata,
        }
    }
}

impl From<Notification> for NotificationSummaryDto {
    fn from(entity: Notification) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            user_id: entity.user_id,
            notification_type: entity.notification_type,
            channel: entity.channel,
            created_at,
        }
    }
}

impl From<CreateNotificationDto> for Notification {
    fn from(dto: CreateNotificationDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            user_id: dto.user_id,
            notification_type: dto.notification_type,
            channel: dto.channel,
            title: dto.title,
            body: dto.body,
            image_url: dto.image_url,
            action_url: dto.action_url,
            action_type: dto.action_type,
            reference_type: dto.reference_type,
            reference_id: dto.reference_id,
            status: dto.status,
            scheduled_at: dto.scheduled_at,
            sent_at: dto.sent_at,
            delivered_at: dto.delivered_at,
            read_at: dto.read_at,
            failed_at: dto.failed_at,
            failure_reason: dto.failure_reason,
            retry_count: dto.retry_count,
            external_id: dto.external_id,
            priority: dto.priority,
            is_actionable: dto.is_actionable,
            action_taken: dto.action_taken,
            action_taken_at: dto.action_taken_at,
            is_dismissed: dto.is_dismissed,
            dismissed_at: dto.dismissed_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Notification> for NotificationResponseDto {
    fn from(entity: &Notification) -> Self {
        Self {
            id: entity.id.clone(),
            user_id: entity.user_id.clone(),
            notification_type: entity.notification_type.clone(),
            channel: entity.channel.clone(),
            title: entity.title.clone(),
            body: entity.body.clone(),
            image_url: entity.image_url.clone(),
            action_url: entity.action_url.clone(),
            action_type: entity.action_type.clone(),
            reference_type: entity.reference_type.clone(),
            reference_id: entity.reference_id.clone(),
            status: entity.status.clone(),
            scheduled_at: entity.scheduled_at.clone(),
            sent_at: entity.sent_at.clone(),
            delivered_at: entity.delivered_at.clone(),
            read_at: entity.read_at.clone(),
            failed_at: entity.failed_at.clone(),
            failure_reason: entity.failure_reason.clone(),
            retry_count: entity.retry_count.clone(),
            external_id: entity.external_id.clone(),
            priority: entity.priority.clone(),
            is_actionable: entity.is_actionable.clone(),
            action_taken: entity.action_taken.clone(),
            action_taken_at: entity.action_taken_at.clone(),
            is_dismissed: entity.is_dismissed.clone(),
            dismissed_at: entity.dismissed_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateNotificationDto> for Notification {
    fn from_create_dto(dto: CreateNotificationDto) -> backbone_core::ServiceResult<Self> {
        Ok(Notification::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateNotificationDto> for Notification {
    fn apply_update(mut self, dto: UpdateNotificationDto) -> backbone_core::ServiceResult<Self> {
        self.user_id = dto.user_id;
        self.notification_type = dto.notification_type;
        self.channel = dto.channel;
        self.title = dto.title;
        self.body = dto.body;
        self.image_url = dto.image_url;
        self.action_url = dto.action_url;
        self.action_type = dto.action_type;
        self.reference_type = dto.reference_type;
        self.reference_id = dto.reference_id;
        self.status = dto.status;
        self.scheduled_at = dto.scheduled_at;
        self.sent_at = dto.sent_at;
        self.delivered_at = dto.delivered_at;
        self.read_at = dto.read_at;
        self.failed_at = dto.failed_at;
        self.failure_reason = dto.failure_reason;
        self.retry_count = dto.retry_count;
        self.external_id = dto.external_id;
        self.priority = dto.priority;
        self.is_actionable = dto.is_actionable;
        self.action_taken = dto.action_taken;
        self.action_taken_at = dto.action_taken_at;
        self.is_dismissed = dto.is_dismissed;
        self.dismissed_at = dto.dismissed_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Notification here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

