//! NotificationPreference DTOs (Data Transfer Objects)
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::NotificationPreference;
use crate::domain::entity::NotificationCategory;
use crate::domain::entity::NotificationChannel;
use crate::domain::entity::PreferenceStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new NotificationPreference
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateNotificationPreferenceDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    pub channel: NotificationChannel,
    pub category: NotificationCategory,
    pub status: PreferenceStatus,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_enabled: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub quiet_hours_enabled: bool,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quiet_start: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quiet_end: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub frequency: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_per_day: Option<i32>,
    pub data: serde_json::Value,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a NotificationPreference
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateNotificationPreferenceDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    pub channel: NotificationChannel,
    pub category: NotificationCategory,
    pub status: PreferenceStatus,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_enabled: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub quiet_hours_enabled: bool,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quiet_start: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 5)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quiet_end: Option<String>,
    #[cfg_attr(feature = "validation", validate(range(max = 20)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub frequency: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_per_day: Option<i32>,
    pub data: serde_json::Value,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a NotificationPreference
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchNotificationPreferenceDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel: Option<NotificationChannel>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<NotificationCategory>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<PreferenceStatus>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_enabled: Option<bool>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quiet_hours_enabled: Option<bool>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quiet_start: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quiet_end: Option<String>,
    #[cfg_attr(feature = "validation", validate(nested))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub frequency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_per_day: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl PatchNotificationPreferenceDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.user_id.is_some() || self.channel.is_some() || self.category.is_some() || self.status.is_some() || self.is_enabled.is_some() || self.quiet_hours_enabled.is_some() || self.quiet_start.is_some() || self.quiet_end.is_some() || self.frequency.is_some() || self.max_per_day.is_some() || self.data.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for NotificationPreference entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct NotificationPreferenceResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub user_id: Uuid,
    pub channel: NotificationChannel,
    pub category: NotificationCategory,
    pub status: PreferenceStatus,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_enabled: bool,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub quiet_hours_enabled: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quiet_start: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quiet_end: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub frequency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_per_day: Option<i32>,
    pub data: serde_json::Value,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for NotificationPreference entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct NotificationPreferenceListResponseDto {
    /// List of items
    pub items: Vec<NotificationPreferenceResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl NotificationPreferenceListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<NotificationPreferenceResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct NotificationPreferenceSummaryDto {
    pub id: Uuid,
    pub user_id: Uuid,
    pub channel: NotificationChannel,
    pub category: NotificationCategory,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<NotificationPreference> for NotificationPreferenceResponseDto {
    fn from(entity: NotificationPreference) -> Self {
        Self {
            id: entity.id,
            user_id: entity.user_id,
            channel: entity.channel,
            category: entity.category,
            status: entity.status,
            is_enabled: entity.is_enabled,
            quiet_hours_enabled: entity.quiet_hours_enabled,
            quiet_start: entity.quiet_start,
            quiet_end: entity.quiet_end,
            frequency: entity.frequency,
            max_per_day: entity.max_per_day,
            data: entity.data,
        }
    }
}

impl From<NotificationPreference> for NotificationPreferenceSummaryDto {
    fn from(entity: NotificationPreference) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            user_id: entity.user_id,
            channel: entity.channel,
            category: entity.category,
            created_at,
        }
    }
}

impl From<CreateNotificationPreferenceDto> for NotificationPreference {
    fn from(dto: CreateNotificationPreferenceDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            user_id: dto.user_id,
            channel: dto.channel,
            category: dto.category,
            status: dto.status,
            is_enabled: dto.is_enabled,
            quiet_hours_enabled: dto.quiet_hours_enabled,
            quiet_start: dto.quiet_start,
            quiet_end: dto.quiet_end,
            frequency: dto.frequency,
            max_per_day: dto.max_per_day,
            data: dto.data,
        }
    }
}

impl From<&NotificationPreference> for NotificationPreferenceResponseDto {
    fn from(entity: &NotificationPreference) -> Self {
        Self {
            id: entity.id.clone(),
            user_id: entity.user_id.clone(),
            channel: entity.channel.clone(),
            category: entity.category.clone(),
            status: entity.status.clone(),
            is_enabled: entity.is_enabled.clone(),
            quiet_hours_enabled: entity.quiet_hours_enabled.clone(),
            quiet_start: entity.quiet_start.clone(),
            quiet_end: entity.quiet_end.clone(),
            frequency: entity.frequency.clone(),
            max_per_day: entity.max_per_day.clone(),
            data: entity.data.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateNotificationPreferenceDto> for NotificationPreference {
    fn from_create_dto(dto: CreateNotificationPreferenceDto) -> backbone_core::ServiceResult<Self> {
        Ok(NotificationPreference::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateNotificationPreferenceDto> for NotificationPreference {
    fn apply_update(mut self, dto: UpdateNotificationPreferenceDto) -> backbone_core::ServiceResult<Self> {
        self.user_id = dto.user_id;
        self.channel = dto.channel;
        self.category = dto.category;
        self.status = dto.status;
        self.is_enabled = dto.is_enabled;
        self.quiet_hours_enabled = dto.quiet_hours_enabled;
        self.quiet_start = dto.quiet_start;
        self.quiet_end = dto.quiet_end;
        self.frequency = dto.frequency;
        self.max_per_day = dto.max_per_day;
        self.data = dto.data;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to NotificationPreference here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

