//! Notification DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Notification;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::NotifChannel;
use crate::domain::entity::NotificationStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Notification
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateNotificationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "event_id")]
    pub event_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "event_type")]
    pub event_type: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "template_id")]
    pub template_id: Option<Uuid>,
    pub channel: NotifChannel,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "recipient_party_id")]
    pub recipient_party_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "recipient_address")]
    pub recipient_address: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    pub status: NotificationStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "message_id")]
    pub message_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "failure_reason")]
    pub failure_reason: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Notification
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateNotificationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "event_id")]
    pub event_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "event_type")]
    pub event_type: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "template_id")]
    pub template_id: Option<Uuid>,
    pub channel: NotifChannel,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "recipient_party_id")]
    pub recipient_party_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "recipient_address")]
    pub recipient_address: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    pub status: NotificationStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "message_id")]
    pub message_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "failure_reason")]
    pub failure_reason: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Notification
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchNotificationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "event_id")]
    pub event_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "event_type")]
    pub event_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "template_id")]
    pub template_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub channel: Option<NotifChannel>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "recipient_party_id")]
    pub recipient_party_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "recipient_address")]
    pub recipient_address: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<NotificationStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "message_id")]
    pub message_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "failure_reason")]
    pub failure_reason: Option<String>,
}

impl PatchNotificationDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.event_id.is_some() || self.event_type.is_some() || self.template_id.is_some() || self.channel.is_some() || self.recipient_party_id.is_some() || self.recipient_address.is_some() || self.subject.is_some() || self.body.is_some() || self.status.is_some() || self.message_id.is_some() || self.failure_reason.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Notification entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct NotificationResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub event_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub event_type: String,
    pub template_id: Option<Uuid>,
    pub channel: NotifChannel,
    pub recipient_party_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub recipient_address: String,
    pub subject: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body: String,
    pub status: NotificationStatus,
    pub message_id: Option<Uuid>,
    pub failure_reason: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Notification entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct NotificationListResponseDto {
    /// List of items
    pub items: Vec<NotificationResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl NotificationListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<NotificationResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct NotificationSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub event_id: Uuid,
    pub event_type: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Notification> for NotificationResponseDto {
    fn from(entity: Notification) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            event_id: entity.event_id,
            event_type: entity.event_type,
            template_id: entity.template_id,
            channel: entity.channel,
            recipient_party_id: entity.recipient_party_id,
            recipient_address: entity.recipient_address,
            subject: entity.subject,
            body: entity.body,
            status: entity.status,
            message_id: entity.message_id,
            failure_reason: entity.failure_reason,
            metadata: entity.metadata,
        }
    }
}

impl From<Notification> for NotificationSummaryDto {
    fn from(entity: Notification) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            event_id: entity.event_id,
            event_type: entity.event_type,
            created_at,
        }
    }
}

impl From<CreateNotificationDto> for Notification {
    fn from(dto: CreateNotificationDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            event_id: dto.event_id,
            event_type: dto.event_type,
            template_id: dto.template_id,
            channel: dto.channel,
            recipient_party_id: dto.recipient_party_id,
            recipient_address: dto.recipient_address,
            subject: dto.subject,
            body: dto.body,
            status: dto.status,
            message_id: dto.message_id,
            failure_reason: dto.failure_reason,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Notification> for NotificationResponseDto {
    fn from(entity: &Notification) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            event_id: entity.event_id.clone(),
            event_type: entity.event_type.clone(),
            template_id: entity.template_id.clone(),
            channel: entity.channel.clone(),
            recipient_party_id: entity.recipient_party_id.clone(),
            recipient_address: entity.recipient_address.clone(),
            subject: entity.subject.clone(),
            body: entity.body.clone(),
            status: entity.status.clone(),
            message_id: entity.message_id.clone(),
            failure_reason: entity.failure_reason.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateNotificationDto> for Notification {
    fn from_create_dto(dto: CreateNotificationDto) -> backbone_core::ServiceResult<Self> {
        Ok(Notification::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateNotificationDto> for Notification {
    fn apply_update(mut self, dto: UpdateNotificationDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.event_id = dto.event_id;
        self.event_type = dto.event_type;
        self.template_id = dto.template_id;
        self.channel = dto.channel;
        self.recipient_party_id = dto.recipient_party_id;
        self.recipient_address = dto.recipient_address;
        self.subject = dto.subject;
        self.body = dto.body;
        self.status = dto.status;
        self.message_id = dto.message_id;
        self.failure_reason = dto.failure_reason;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Notification here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
