//! GraphQL schema composition for Notification module
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Provides both standalone `build_schema()` and composable `inject_services()`
//! methods. Use `inject_services()` to compose module GraphQL services into
//! a shared app-level schema.

use std::sync::Arc;
use async_graphql::*;

use super::{NotificationQuery, NotificationMutation};
use super::{NotificationPreferenceQuery, NotificationPreferenceMutation};

use crate::application::service::NotificationService;
use crate::application::service::NotificationPreferenceService;

/// Merged Query root for Notification module
#[derive(MergedObject, Default)]
pub struct NotificationQuery(NotificationQuery, NotificationPreferenceQuery);

/// Merged Mutation root for Notification module
#[derive(MergedObject, Default)]
pub struct NotificationMutation(NotificationMutation, NotificationPreferenceMutation);

/// Inject all Notification services into a schema builder
pub fn inject_services<Q: ObjectType + 'static, M: ObjectType + 'static, S: SubscriptionType + 'static>(
    builder: SchemaBuilder<Q, M, S>,
    module: &crate::NotificationModule,
) -> SchemaBuilder<Q, M, S> {
    builder
        .data(module.notification_service.clone())
        .data(module.notification_preference_service.clone())
}

/// Build the GraphQL schema for Notification module (standalone)
pub fn build_schema(module: &crate::NotificationModule) -> Schema<NotificationQuery, NotificationMutation, EmptySubscription> {
    let builder = Schema::build(NotificationQuery::default(), NotificationMutation::default(), EmptySubscription);
    inject_services(builder, module).finish()
}
