//! gRPC service registration
//!
//! Generated by backbone-schema. Do not edit manually.

use tonic::transport::Server;

use super::grpc::notification_grpc_service::NotificationGrpcService;
use super::grpc::notification_preference_grpc_service::NotificationPreferenceGrpcService;

/// gRPC server for Notification module
pub struct NotificationGrpcServer {
    notification_service: NotificationGrpcService,
    notification_preference_service: NotificationPreferenceGrpcService,
}

impl NotificationGrpcServer {
    /// Create a new gRPC server from module
    pub fn new(module: &super::NotificationModule) -> Self {
        Self {
            notification_service: NotificationGrpcService::new(module.notification_service.clone()),
            notification_preference_service: NotificationPreferenceGrpcService::new(module.notification_preference_service.clone()),
        }
    }

    /// Start the gRPC server
    pub async fn serve(self, addr: std::net::SocketAddr) -> Result<(), tonic::transport::Error> {
        Server::builder()
            .add_service(self.notification_service.into_service())
            .add_service(self.notification_preference_service.into_service())
            .serve(addr)
            .await
    }
}
