//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod notification_domain_policy;
pub mod notification_template_domain_policy;

pub use notification_domain_policy::NotificationDomainPolicy;
pub use notification_template_domain_policy::NotificationTemplateDomainPolicy;

// <<< CUSTOM
// END CUSTOM
