//! Domain policies
//!
//! Generated by backbone-schema. Do not edit manually.

pub mod notification_domain_policy;
pub mod notification_preference_domain_policy;

pub use notification_domain_policy::NotificationDomainPolicy;
pub use notification_preference_domain_policy::NotificationPreferenceDomainPolicy;

// <<< CUSTOM
// END CUSTOM
