//! Application services
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

mod notification_service;
mod notification_preference_service;

// <<< CUSTOM
// END CUSTOM

pub use notification_service::NotificationService;
pub use notification_preference_service::NotificationPreferenceService;
// <<< CUSTOM
// END CUSTOM
