//! Query handlers for Notification module
//!
//! Queries represent read operations that don't modify state.
//! Part of CQRS pattern implementation.
//!
//! Generated by backbone-schema. Custom code sections are preserved.

// Queries will be generated here by backbone-schema
// Use: backbone schema generate notification --target cqrs
