-- Notification Seed Data
-- Generated by backbone-schema
--
-- This file contains initial seed data for the notifications table.
-- Customize this file to add your initial data.

-- INSERT INTO notifications (
--     id,
--     user_id,
--     notification_type,
--     channel,
--     title,
--     body,
--     image_url,
--     action_url,
--     action_type,
--     reference_type,
--     reference_id,
--     status,
--     scheduled_at,
--     sent_at,
--     delivered_at,
--     read_at,
--     failed_at,
--     failure_reason,
--     retry_count,
--     external_id,
--     priority,
--     is_actionable,
--     action_taken,
--     action_taken_at,
--     is_dismissed,
--     dismissed_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO notifications (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

