-- Notification Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the notification.notifications table.
-- Customize this file to add your initial data.

-- INSERT INTO notification.notifications (
--     id,
--     company_id,
--     event_id,
--     event_type,
--     template_id,
--     channel,
--     recipient_party_id,
--     recipient_address,
--     subject,
--     body,
--     status,
--     message_id,
--     failure_reason,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO notification.notifications (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

