-- NotificationPreference Seed Data
-- Generated by backbone-schema
--
-- This file contains initial seed data for the notification_preferences table.
-- Customize this file to add your initial data.

-- INSERT INTO notification_preferences (
--     id,
--     user_id,
--     channel,
--     category,
--     status,
--     is_enabled,
--     quiet_hours_enabled,
--     quiet_start,
--     quiet_end,
--     frequency,
--     max_per_day,
--     data
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO notification_preferences (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

