-- NotificationTemplate Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the notification.notification_templates table.
-- Customize this file to add your initial data.

-- INSERT INTO notification.notification_templates (
--     id,
--     company_id,
--     event_type,
--     channel,
--     name,
--     subject_template,
--     body_template,
--     is_active,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert reference data
-- Uncomment and modify the following:

-- INSERT INTO notification.notification_templates (id, code, name, is_active, created_at, updated_at) VALUES
--     (gen_random_uuid(), 'SAMPLE1', 'Sample 1', true, NOW(), NOW()),
--     (gen_random_uuid(), 'SAMPLE2', 'Sample 2', true, NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

