-- Enum types for notification module
-- Generated by backbone-schema

-- Create notification_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_type') THEN
        CREATE TYPE notification_type AS ENUM ('order', 'payment', 'promo', 'marketing', 'system', 'reminder', 'alert');
    END IF;
END
$$;

-- Create notification_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_status') THEN
        CREATE TYPE notification_status AS ENUM ('pending', 'scheduled', 'sent', 'delivered', 'read', 'failed', 'cancelled');
    END IF;
END
$$;

-- Create notification_priority enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_priority') THEN
        CREATE TYPE notification_priority AS ENUM ('low', 'normal', 'high', 'urgent');
    END IF;
END
$$;

-- Create digest_frequency enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'digest_frequency') THEN
        CREATE TYPE digest_frequency AS ENUM ('daily', 'weekly');
    END IF;
END
$$;

-- Create notification_channel enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_channel') THEN
        CREATE TYPE notification_channel AS ENUM ('push', 'sms', 'email', 'whatsapp', 'in_app');
    END IF;
END
$$;

-- Create notification_category enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_category') THEN
        CREATE TYPE notification_category AS ENUM ('order', 'promo', 'payment', 'delivery', 'loyalty', 'system', 'marketing', 'reminder');
    END IF;
END
$$;

-- Create preference_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'preference_status') THEN
        CREATE TYPE preference_status AS ENUM ('enabled', 'disabled');
    END IF;
END
$$;

