-- Migration: Create notifications table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS notifications (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    notification_type notification_type NOT NULL,
    channel notification_channel NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    image_url TEXT,
    action_url TEXT,
    action_type TEXT,
    reference_type TEXT,
    reference_id UUID,
    status notification_status NOT NULL DEFAULT 'pending',
    scheduled_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    read_at TIMESTAMPTZ,
    failed_at TIMESTAMPTZ,
    failure_reason TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0,
    external_id TEXT,
    priority notification_priority NOT NULL DEFAULT 'normal',
    is_actionable BOOLEAN NOT NULL DEFAULT FALSE,
    action_taken BOOLEAN NOT NULL DEFAULT FALSE,
    action_taken_at TIMESTAMPTZ,
    is_dismissed BOOLEAN NOT NULL DEFAULT FALSE,
    dismissed_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id_status_created_at ON notifications (user_id, status, ((metadata->>'created_at')));

CREATE INDEX IF NOT EXISTS idx_notifications_user_id_notification_type_created_at ON notifications (user_id, notification_type, ((metadata->>'created_at')));

CREATE INDEX IF NOT EXISTS idx_notifications_status_scheduled_at ON notifications (status, scheduled_at);

CREATE INDEX IF NOT EXISTS idx_notifications_reference_type_reference_id ON notifications (reference_type, reference_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_notifications_metadata_gin ON notifications USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_notifications_metadata_deleted_at ON notifications ((metadata->>'deleted_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION notifications_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS notifications_insert_audit ON notifications;
CREATE TRIGGER notifications_insert_audit BEFORE INSERT ON notifications
    FOR EACH ROW EXECUTE FUNCTION notifications_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS notifications_update_audit ON notifications;
CREATE TRIGGER notifications_update_audit BEFORE UPDATE ON notifications
    FOR EACH ROW EXECUTE FUNCTION notifications_audit_timestamp();

