-- Migration: Create notification_preferences table
-- Generated by backbone-schema

CREATE TABLE IF NOT EXISTS notification_preferences (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    channel notification_channel NOT NULL,
    category notification_category NOT NULL,
    status preference_status NOT NULL DEFAULT 'enabled',
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    quiet_hours_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    quiet_start TEXT,
    quiet_end TEXT,
    frequency TEXT,
    max_per_day INTEGER,
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_notification_preferences_user_id_channel_category ON notification_preferences (user_id, channel, category) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_notification_preferences_user_id_is_enabled ON notification_preferences (user_id, is_enabled);

CREATE INDEX IF NOT EXISTS idx_notification_preferences_channel_category ON notification_preferences (channel, category);

