-- Foreign key constraints for notification module
-- Generated by backbone-schema

ALTER TABLE notifications ADD CONSTRAINT fk_notifications_user_id FOREIGN KEY (user_id) REFERENCES sapiens.users (id);

ALTER TABLE notification_preferences ADD CONSTRAINT fk_notification_preferences_user_id FOREIGN KEY (user_id) REFERENCES sapiens.users (id);

