-- Company RLS fence for notification module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for notification.notifications
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE notification.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification.notifications FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS notifications_company_isolation ON notification.notifications;
CREATE POLICY notifications_company_isolation ON notification.notifications
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for notification.notification_templates
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE notification.notification_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification.notification_templates FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS notification_templates_company_isolation ON notification.notification_templates;
CREATE POLICY notification_templates_company_isolation ON notification.notification_templates
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

