-- Migration: Create notifications table
-- Generated by metaphor-schema

-- Create notif_channel enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notif_channel') THEN
        CREATE TYPE notif_channel AS ENUM ('whatsapp', 'email', 'sms');
    END IF;
END
$$;

-- Create notification_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_status') THEN
        CREATE TYPE notification_status AS ENUM ('pending', 'sent', 'delivered', 'undelivered', 'failed', 'skipped');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS notification;

CREATE TABLE IF NOT EXISTS notification.notifications (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    event_id UUID NOT NULL,
    event_type TEXT NOT NULL,
    template_id UUID,
    channel notif_channel NOT NULL,
    recipient_party_id UUID,
    recipient_address TEXT NOT NULL,
    subject TEXT,
    body TEXT NOT NULL,
    status notification_status NOT NULL DEFAULT 'pending',
    message_id UUID,
    failure_reason TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_notifications_event_id_recipient_address ON notification.notifications (event_id, recipient_address);

CREATE INDEX IF NOT EXISTS idx_notifications_company_id_status ON notification.notifications (company_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_notifications_metadata_gin ON notification.notifications USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_notifications_metadata_deleted_at ON notification.notifications ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_notifications_metadata_created_at ON notification.notifications ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_notifications_metadata_updated_at ON notification.notifications ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION notification.notifications_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS notifications_insert_audit ON notification.notifications;
CREATE TRIGGER notifications_insert_audit BEFORE INSERT ON notification.notifications
    FOR EACH ROW EXECUTE FUNCTION notification.notifications_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS notifications_update_audit ON notification.notifications;
CREATE TRIGGER notifications_update_audit BEFORE UPDATE ON notification.notifications
    FOR EACH ROW EXECUTE FUNCTION notification.notifications_audit_timestamp();
