-- Enum types for notification module
-- Generated by metaphor-schema

-- Create notification_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notification_status') THEN
        CREATE TYPE notification_status AS ENUM ('pending', 'sent', 'delivered', 'undelivered', 'failed', 'skipped');
    END IF;
END
$$;

-- Create notif_channel enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'notif_channel') THEN
        CREATE TYPE notif_channel AS ENUM ('whatsapp', 'email', 'sms');
    END IF;
END
$$;

