//! Domain events
//!
//! Generated by backbone-schema. Do not edit manually.

pub mod notification_events;
pub mod notification_event_handlers;
pub mod notification_preference_events;
pub mod notification_preference_event_handlers;

pub use notification_events::{NotificationEvent, NotificationEventPublisher, NoopNotificationEventPublisher};
pub use notification_event_handlers::NotificationEventHandler;
pub use notification_preference_events::{NotificationPreferenceEvent, NotificationPreferenceEventPublisher, NoopNotificationPreferenceEventPublisher};
pub use notification_preference_event_handlers::NotificationPreferenceEventHandler;

// <<< CUSTOM
// END CUSTOM
