//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod notification_events;
pub mod notification_event_handlers;
pub mod notification_template_events;
pub mod notification_template_event_handlers;

pub use notification_events::{NotificationEvent, NotificationEventPublisher, NoopNotificationEventPublisher};
pub use notification_event_handlers::NotificationEventHandler;
pub use notification_template_events::{NotificationTemplateEvent, NotificationTemplateEventPublisher, NoopNotificationTemplateEventPublisher};
pub use notification_template_event_handlers::NotificationTemplateEventHandler;

// <<< CUSTOM
// END CUSTOM
