//! Event subscriber type aliases for Notification module
//!
//! Generated by backbone-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::NotificationEvent;
use crate::domain::event::NotificationPreferenceEvent;

/// Subscriber for Notification events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type NotificationEventSubscriber = GenericEventSubscriber<NotificationEvent>;

/// Subscriber for NotificationPreference events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type NotificationPreferenceEventSubscriber = GenericEventSubscriber<NotificationPreferenceEvent>;

// <<< CUSTOM
// END CUSTOM
