//! Event subscriber type aliases for Notification module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::NotificationEvent;
use crate::domain::event::NotificationTemplateEvent;

/// Subscriber for Notification events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type NotificationEventSubscriber = GenericEventSubscriber<NotificationEvent>;

/// Subscriber for NotificationTemplate events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type NotificationTemplateEventSubscriber = GenericEventSubscriber<NotificationTemplateEvent>;

// <<< CUSTOM
// END CUSTOM
