//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod notification_repository;
pub mod notification_template_repository;

// Re-exports
pub use notification_repository::{
    NotificationRepository,
    NotificationPaginationParams,
    NotificationPaginatedResult,
    NotificationFilter,
};
pub use notification_template_repository::{
    NotificationTemplateRepository,
    NotificationTemplatePaginationParams,
    NotificationTemplatePaginatedResult,
    NotificationTemplateFilter,
};
