//! Repository trait for NotificationPreference aggregate
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the NotificationPreference aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{NotificationPreference, NotificationCategory, NotificationChannel, PreferenceStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct NotificationPreferencePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl NotificationPreferencePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct NotificationPreferencePaginatedResult {
    pub data: Vec<NotificationPreference>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct NotificationPreferenceFilter {
    pub user_id: Option<Uuid>,
    pub channel: Option<NotificationChannel>,
    pub category: Option<NotificationCategory>,
    pub status: Option<PreferenceStatus>,
    pub is_enabled: Option<bool>,
    pub quiet_hours_enabled: Option<bool>,
    pub quiet_start: Option<String>,
    pub quiet_end: Option<String>,
    pub frequency: Option<String>,
}

impl NotificationPreferenceFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.user_id.is_some() || self.channel.is_some() || self.category.is_some() || self.status.is_some() || self.is_enabled.is_some() || self.quiet_hours_enabled.is_some() || self.quiet_start.is_some() || self.quiet_end.is_some() || self.frequency.is_some()
    }
}

/// Repository trait for NotificationPreference aggregate
///
/// This trait defines the persistence contract for NotificationPreference entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait NotificationPreferenceRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new notification_preference entity
    async fn save(&self, entity: &NotificationPreference) -> Result<NotificationPreference>;

    /// Find notification_preference by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<NotificationPreference>>;

    /// Find all notification_preference entities
    async fn find_all(&self) -> Result<Vec<NotificationPreference>>;

    /// Update notification_preference by ID
    async fn update(&self, id: &str, entity: &NotificationPreference) -> Result<Option<NotificationPreference>>;

    /// Delete notification_preference by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List notification_preference with pagination
    async fn list(&self, params: NotificationPreferencePaginationParams) -> Result<NotificationPreferencePaginatedResult>;

    /// List notification_preference with pagination and filters
    async fn list_with_filters(&self, params: NotificationPreferencePaginationParams, filters: NotificationPreferenceFilter) -> Result<NotificationPreferencePaginatedResult>;

    /// Count all notification_preference entities
    async fn count(&self) -> Result<u64>;

    /// Count notification_preference entities matching filters
    async fn count_with_filters(&self, filters: NotificationPreferenceFilter) -> Result<u64>;

    /// Check if notification_preference exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save notification_preference entities
    async fn bulk_save(&self, entities: &[NotificationPreference]) -> Result<Vec<NotificationPreference>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
