//! Repository trait for Notification aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Notification aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Notification, NotifChannel, NotificationStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct NotificationPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl NotificationPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct NotificationPaginatedResult {
    pub data: Vec<Notification>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct NotificationFilter {
    pub company_id: Option<Uuid>,
    pub event_id: Option<Uuid>,
    pub event_type: Option<String>,
    pub template_id: Option<Uuid>,
    pub channel: Option<NotifChannel>,
    pub recipient_party_id: Option<Uuid>,
    pub recipient_address: Option<String>,
    pub subject: Option<String>,
    pub body: Option<String>,
    pub status: Option<NotificationStatus>,
    pub message_id: Option<Uuid>,
    pub failure_reason: Option<String>,
}

impl NotificationFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.event_id.is_some() || self.event_type.is_some() || self.template_id.is_some() || self.channel.is_some() || self.recipient_party_id.is_some() || self.recipient_address.is_some() || self.subject.is_some() || self.body.is_some() || self.status.is_some() || self.message_id.is_some() || self.failure_reason.is_some()
    }
}

/// Repository trait for Notification aggregate
///
/// This trait defines the persistence contract for Notification entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait NotificationRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new notification entity
    async fn save(&self, entity: &Notification) -> Result<Notification>;

    /// Find notification by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Notification>>;

    /// Find all notification entities
    async fn find_all(&self) -> Result<Vec<Notification>>;

    /// Update notification by ID
    async fn update(&self, id: &str, entity: &Notification) -> Result<Option<Notification>>;

    /// Delete notification by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List notification with pagination
    async fn list(&self, params: NotificationPaginationParams) -> Result<NotificationPaginatedResult>;

    /// List notification with pagination and filters
    async fn list_with_filters(&self, params: NotificationPaginationParams, filters: NotificationFilter) -> Result<NotificationPaginatedResult>;

    /// Count all notification entities
    async fn count(&self) -> Result<u64>;

    /// Count notification entities matching filters
    async fn count_with_filters(&self, filters: NotificationFilter) -> Result<u64>;

    /// Check if notification exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete notification by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted notification by ID
    async fn restore(&self, id: &str) -> Result<Option<Notification>>;

    /// List soft-deleted notification entities
    async fn list_deleted(&self, params: NotificationPaginationParams) -> Result<NotificationPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save notification entities
    async fn bulk_save(&self, entities: &[Notification]) -> Result<Vec<Notification>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
