//! Repository for NotificationPreference entities
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<NotificationPreference, backbone_orm::HardDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::NotificationPreference;

/// Table name for NotificationPreference entities
pub const TABLE_NAME: &str = "notification_preferences";

/// Repository for NotificationPreference entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct NotificationPreferenceRepository(
    backbone_orm::GenericCrudRepository<NotificationPreference, backbone_orm::HardDelete>,
);

impl std::ops::Deref for NotificationPreferenceRepository {
    type Target = backbone_orm::GenericCrudRepository<NotificationPreference, backbone_orm::HardDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl NotificationPreferenceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(NotificationPreferenceRepository, NotificationPreference, no_soft_delete);
