//! Repository for Notification entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written Notification SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Notification, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::Notification;

/// Table name for Notification entities
pub const TABLE_NAME: &str = "notification.notifications";

/// Repository for Notification entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct NotificationRepository(
    backbone_orm::GenericCrudRepository<Notification, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for NotificationRepository {
    type Target = backbone_orm::GenericCrudRepository<Notification, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl NotificationRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a per-recipient dedup claim writes.
///
/// Mirrors the raw column shape rather than the `Notification` entity: `channel` binds as `&str` and is
/// cast at the DB (`$6::notif_channel`), so a bad value fails as a DB error rather than a deserialize
/// panic.
pub struct NewNotificationRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub event_id: Uuid,
    pub event_type: &'a str,
    pub template_id: Uuid,
    pub channel: &'a str,
    pub recipient_party_id: Option<Uuid>,
    pub recipient_address: &'a str,
    pub subject: Option<&'a String>,
    pub body: &'a str,
}

/// A stranded `pending` notification, as the re-drive sweep reads it.
pub struct PendingNotificationRow {
    pub id: Uuid,
    pub event_id: Uuid,
    pub company_id: Uuid,
    pub channel: String,
    pub recipient_party_id: Option<Uuid>,
    pub recipient_address: String,
    pub subject: Option<String>,
    pub body: String,
}

/// The identity a delivery receipt resolved to.
pub struct DeliveredRow {
    pub id: Uuid,
    pub event_id: Uuid,
}

/// Hand-written Notification SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl NotificationRepository {
    /// Claim the (event_id, recipient_address) dedup slot. `Ok(None)` = this recipient was already
    /// notified for this event (a redelivered domain event), and the caller counts it as deduped.
    ///
    /// Runs outside a transaction on the pool via `fetch_optional_scalar_scoped`; the caller wraps it in
    /// `with_company_scope(Some(company_id))` so the INSERT passes the WITH CHECK fence (ADR-0008).
    pub async fn claim_recipient(
        &self,
        pool: &PgPool,
        n: &NewNotificationRow<'_>,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        company_scope::fetch_optional_scalar_scoped(
            pool,
            sqlx::query_scalar(
                r#"INSERT INTO notification.notifications
                     (id, company_id, event_id, event_type, template_id, channel, recipient_party_id,
                      recipient_address, subject, body, status)
                   VALUES ($1,$2,$3,$4,$5,$6::notif_channel,$7,$8,$9,$10,'pending'::notification_status)
                   ON CONFLICT (event_id, recipient_address) DO NOTHING
                   RETURNING id"#,
            )
            .bind(n.id).bind(n.company_id).bind(n.event_id).bind(n.event_type).bind(n.template_id)
            .bind(n.channel).bind(n.recipient_party_id).bind(n.recipient_address)
            .bind(n.subject).bind(n.body),
        )
        .await
    }

    /// Record a successful dispatch. State-guarded on `pending`.
    ///
    /// ID-only — rides the caller's company scope (every call site wraps in `with_company_scope`).
    pub async fn mark_sent(
        &self,
        pool: &PgPool,
        notification_id: Uuid,
        message_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE notification.notifications SET status='sent'::notification_status, message_id=$2
                   WHERE id=$1 AND status='pending'::notification_status"#,
            )
            .bind(notification_id).bind(message_id),
        )
        .await?;
        Ok(())
    }

    /// Record a dispatch rejection. State-guarded on `pending`. Same ID-only, caller-scoped contract as
    /// [`Self::mark_sent`].
    pub async fn mark_failed(
        &self,
        pool: &PgPool,
        notification_id: Uuid,
        reason: &str,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE notification.notifications SET status='failed'::notification_status, failure_reason=$2
                   WHERE id=$1 AND status='pending'::notification_status"#,
            )
            .bind(notification_id).bind(reason),
        )
        .await?;
        Ok(())
    }

    /// The oldest notifications stranded in `pending` — what the re-drive sweep re-dispatches.
    ///
    /// The sweep carries no company of its own — it reads under the AMBIENT scope, so the CALLER (the
    /// scheduler) MUST wrap this in `with_company_scope(Some(company))` and drive it once per company;
    /// otherwise the RLS fence returns nothing and the stranded rows are never re-driven.
    pub async fn list_pending(
        &self,
        pool: &PgPool,
        limit: i64,
    ) -> Result<Vec<PendingNotificationRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT id, event_id, company_id, channel::text AS channel, recipient_party_id,
                          recipient_address, subject, body
                   FROM notification.notifications
                   WHERE status='pending'::notification_status AND (metadata->>'deleted_at') IS NULL
                   ORDER BY (metadata->>'created_at') NULLS FIRST LIMIT $1"#,
            )
            .bind(limit),
        )
        .await?;
        Ok(rows
            .iter()
            .map(|r| PendingNotificationRow {
                id: r.get("id"),
                event_id: r.get("event_id"),
                company_id: r.get("company_id"),
                channel: r.get("channel"),
                recipient_party_id: r.get("recipient_party_id"),
                recipient_address: r.get("recipient_address"),
                subject: r.get("subject"),
                body: r.get("body"),
            })
            .collect())
    }

    /// Apply a provider delivery receipt, correlating by `message_id`. State-guarded on `sent`, so a
    /// redelivered receipt is a no-op (`Ok(None)`). `status` binds as `&str` and is cast at the DB
    /// (`$2::notification_status`).
    ///
    /// Takes the CALLER'S connection so this and the outbox stage commit as one unit. Correlated by
    /// `message_id` alone — this verb has NO company of its own; the caller has already bound the
    /// AMBIENT scope on the tx (`bind_current_company`), so don't re-bind here. The receipt consumer
    /// MUST wrap the whole thing in `with_company_scope(Some(event.company_id))` from the communication
    /// receipt it is reacting to.
    pub async fn apply_delivery_receipt(
        &self,
        conn: &mut sqlx::PgConnection,
        message_id: Uuid,
        status: &str,
        reason: Option<&String>,
    ) -> Result<Option<DeliveredRow>, sqlx::Error> {
        let row = sqlx::query(
            r#"UPDATE notification.notifications
               SET status=$2::notification_status, failure_reason=COALESCE($3, failure_reason)
               WHERE message_id=$1 AND status='sent'::notification_status
               RETURNING id, event_id"#,
        )
        .bind(message_id).bind(status).bind(reason)
        .fetch_optional(conn)
        .await?;
        Ok(row.map(|r| DeliveredRow { id: r.get("id"), event_id: r.get("event_id") }))
    }
}

backbone_core::impl_crud_repository!(NotificationRepository, Notification, soft_delete);
