//! Repository for NotificationTemplate entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written NotificationTemplate SQL (4-layer rule: services orchestrate, repos
//! hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<NotificationTemplate, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::NotificationTemplate;

/// Table name for NotificationTemplate entities
pub const TABLE_NAME: &str = "notification.notification_templates";

/// Repository for NotificationTemplate entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct NotificationTemplateRepository(
    backbone_orm::GenericCrudRepository<NotificationTemplate, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for NotificationTemplateRepository {
    type Target = backbone_orm::GenericCrudRepository<NotificationTemplate, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl NotificationTemplateRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a template definition writes.
///
/// Mirrors the raw column shape rather than the `NotificationTemplate` entity: `channel` binds as
/// `&str` and is cast at the DB (`$4::notif_channel`), so a bad value fails as a DB error rather than
/// a deserialize panic.
pub struct NewTemplateRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub event_type: &'a str,
    pub channel: &'a str,
    pub name: &'a str,
    pub subject_template: Option<&'a String>,
    pub body_template: &'a str,
}

/// The active template a fan-out renders from.
pub struct ActiveTemplateRow {
    pub id: Uuid,
    pub subject_template: Option<String>,
    pub body_template: String,
}

/// Hand-written NotificationTemplate SQL. Lives here (not in the write service) per the module's
/// 4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl NotificationTemplateRepository {
    /// Define the active template for a (company, event_type, channel).
    ///
    /// Runs outside a transaction on the pool via `execute_scoped`; the caller wraps it in
    /// `with_company_scope(Some(company_id))` so the INSERT passes the WITH CHECK fence (ADR-0008).
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to turn
    /// a duplicate event/channel template into a domain error.
    pub async fn insert_template(
        &self,
        pool: &PgPool,
        t: &NewTemplateRow<'_>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO notification.notification_templates
                     (id, company_id, event_type, channel, name, subject_template, body_template, is_active)
                   VALUES ($1,$2,$3,$4::notif_channel,$5,$6,$7,true)"#,
            )
            .bind(t.id).bind(t.company_id).bind(t.event_type).bind(t.channel).bind(t.name)
            .bind(t.subject_template).bind(t.body_template),
        )
        .await?;
        Ok(())
    }

    /// Resolve the active template for a (company, event_type, channel). `Ok(None)` = nothing to send
    /// for this event/channel, and the caller records the recipients as skipped.
    ///
    /// Caller supplies the company scope (`with_company_scope(Some(company_id))`); the explicit
    /// `company_id=$1` is defense-in-depth on top of that fence.
    pub async fn find_active(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        event_type: &str,
        channel: &str,
    ) -> Result<Option<ActiveTemplateRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_scoped(
            pool,
            sqlx::query_as::<_, (Uuid, Option<String>, String)>(
                r#"SELECT id, subject_template, body_template FROM notification.notification_templates
                   WHERE company_id=$1 AND event_type=$2 AND channel=$3::notif_channel AND is_active=true
                     AND (metadata->>'deleted_at') IS NULL
                   LIMIT 1"#,
            )
            .bind(company_id).bind(event_type).bind(channel),
        )
        .await?;
        Ok(row.map(|(id, subject_template, body_template)| ActiveTemplateRow {
            id, subject_template, body_template,
        }))
    }
}

backbone_core::impl_crud_repository!(NotificationTemplateRepository, NotificationTemplate, soft_delete);
