//! Repository for NotificationTemplate entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written NotificationTemplate SQL (4-layer rule: services orchestrate, repos
//! hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<NotificationTemplate, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::org_scope;

use crate::domain::entity::NotificationTemplate;

/// Table name for NotificationTemplate entities
pub const TABLE_NAME: &str = "notification.notification_templates";

/// Repository for NotificationTemplate entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct NotificationTemplateRepository(
    backbone_orm::GenericCrudRepository<NotificationTemplate, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for NotificationTemplateRepository {
    type Target = backbone_orm::GenericCrudRepository<NotificationTemplate, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl NotificationTemplateRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a template definition writes.
///
/// Mirrors the raw column shape rather than the `NotificationTemplate` entity: `channel` binds as
/// `&str` and is cast at the DB (`$4::notif_channel`), so a bad value fails as a DB error rather than
/// a deserialize panic.
pub struct NewTemplateRow<'a> {
    pub id: Uuid,
    pub event_type: &'a str,
    pub channel: &'a str,
    pub name: &'a str,
    pub subject_template: Option<&'a String>,
    pub body_template: &'a str,
}

/// The active template a fan-out renders from.
pub struct ActiveTemplateRow {
    pub id: Uuid,
    pub subject_template: Option<String>,
    pub body_template: String,
}

/// Hand-written NotificationTemplate SQL. Lives here (not in the write service) per the module's
/// 4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl NotificationTemplateRepository {
    /// Define the active template for an (event_type, channel).
    ///
    /// Runs outside a transaction on the pool via `execute_scoped` — transport only: the helper rides
    /// the request-dedicated connection when one is bound (carrying whatever scope the COMPOSING
    /// service set), otherwise executes plainly on the pool. The module invents no scope of its own
    /// (composition-installed tenancy, ADR-0029).
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to turn
    /// a duplicate event/channel template into a domain error. Module tables carry no such unique
    /// themselves; a composing service's tenancy decorator may install a per-unit one.
    pub async fn insert_template(
        &self,
        pool: &PgPool,
        t: &NewTemplateRow<'_>,
    ) -> Result<(), sqlx::Error> {
        org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO notification.notification_templates
                     (id, event_type, channel, name, subject_template, body_template, status)
                   VALUES ($1,$2,$3::notif_channel,$4,$5,$6,'active')"#,
            )
            .bind(t.id).bind(t.event_type).bind(t.channel).bind(t.name)
            .bind(t.subject_template).bind(t.body_template),
        )
        .await?;
        Ok(())
    }

    /// Resolve the active template for an (event_type, channel). `Ok(None)` = nothing to send
    /// for this event/channel, and the caller records the recipients as skipped.
    pub async fn find_active(
        &self,
        pool: &PgPool,
        event_type: &str,
        channel: &str,
    ) -> Result<Option<ActiveTemplateRow>, sqlx::Error> {
        let row = org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT id, subject_template, body_template FROM notification.notification_templates
                   WHERE event_type=$1 AND channel=$2::notif_channel AND status='active'
                     AND (metadata->>'deleted_at') IS NULL
                   LIMIT 1"#,
            )
            .bind(event_type).bind(channel),
        )
        .await?;
        Ok(row.map(|r| ActiveTemplateRow {
            id: r.get("id"),
            subject_template: r.get("subject_template"),
            body_template: r.get("body_template"),
        }))
    }
}

backbone_core::impl_crud_repository!(NotificationTemplateRepository, NotificationTemplate, soft_delete);
