//! Entity validators
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod notification_validator;
pub mod notification_template_validator;

pub use notification_validator::{NotificationValidator, notification_validator};
pub use notification_template_validator::{NotificationTemplateValidator, notification_template_validator};

// <<< CUSTOM
// END CUSTOM
