//! Entity validators
//!
//! Generated by backbone-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::{ValidationError, ValidationErrors, ValidationResult, EntityValidator};

pub mod notification_validator;
pub mod notification_preference_validator;

pub use notification_validator::{NotificationValidator, notification_validator};
pub use notification_preference_validator::{NotificationPreferenceValidator, notification_preference_validator};

// <<< CUSTOM
// END CUSTOM
