//! Validator for Notification entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Notification>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::Notification;

/// Validator type alias for Notification entities.
pub type NotificationValidator = EntityValidator<Notification>;

/// Build a validator for Notification with all schema-defined field rules.
pub fn notification_validator() -> NotificationValidator {
    EntityValidator::new()
        .rule(RequiredString::new("event_type", |e: &Notification| &e.event_type))
        .rule(RequiredString::new("recipient_address", |e: &Notification| &e.recipient_address))
        .rule(OptionalNotBlank::new("subject", |e: &Notification| e.subject.as_deref()))
        .rule(RequiredString::new("body", |e: &Notification| &e.body))
        .rule(OptionalNotBlank::new("failure_reason", |e: &Notification| e.failure_reason.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
