//! Validator for Notification entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Notification>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString, RequiredUuid};
use crate::domain::entity::Notification;

/// Validator type alias for Notification entities.
pub type NotificationValidator = EntityValidator<Notification>;

/// Build a validator for Notification with all schema-defined field rules.
pub fn notification_validator() -> NotificationValidator {
    EntityValidator::new()
        .rule(RequiredUuid::new("user_id", |e: &Notification| &e.user_id))
        .rule(RequiredString::new("title", |e: &Notification| &e.title))
        .rule(RequiredString::new("body", |e: &Notification| &e.body))
        .rule(OptionalNotBlank::new("image_url", |e: &Notification| e.image_url.as_deref()))
        .rule(OptionalNotBlank::new("action_url", |e: &Notification| e.action_url.as_deref()))
        .rule(OptionalNotBlank::new("action_type", |e: &Notification| e.action_type.as_deref()))
        .rule(OptionalNotBlank::new("reference_type", |e: &Notification| e.reference_type.as_deref()))
        .rule(OptionalNotBlank::new("failure_reason", |e: &Notification| e.failure_reason.as_deref()))
        .rule(NonNegative::new("retry_count", |e: &Notification| e.retry_count))
        .rule(OptionalNotBlank::new("external_id", |e: &Notification| e.external_id.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
