//! Validator for NotificationPreference entity
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<NotificationPreference>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredUuid};
use crate::domain::entity::NotificationPreference;

/// Validator type alias for NotificationPreference entities.
pub type NotificationPreferenceValidator = EntityValidator<NotificationPreference>;

/// Build a validator for NotificationPreference with all schema-defined field rules.
pub fn notification_preference_validator() -> NotificationPreferenceValidator {
    EntityValidator::new()
        .rule(RequiredUuid::new("user_id", |e: &NotificationPreference| &e.user_id))
        .rule(OptionalNotBlank::new("quiet_start", |e: &NotificationPreference| e.quiet_start.as_deref()))
        .rule(OptionalNotBlank::new("quiet_end", |e: &NotificationPreference| e.quiet_end.as_deref()))
        .rule(OptionalNotBlank::new("frequency", |e: &NotificationPreference| e.frequency.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
