//! Auth policies and guards
//!
//! Generated by backbone-schema. Do not edit manually.

pub mod notification_auth;
pub mod notification_preference_auth;

pub use notification_auth::{NotificationPolicy, NotificationGuard, NotificationServiceGuard};
pub use notification_preference_auth::{NotificationPreferencePolicy, NotificationPreferenceGuard, NotificationPreferenceServiceGuard};

// <<< CUSTOM
// END CUSTOM
