//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod notification_auth;
pub mod notification_template_auth;

pub use notification_auth::{NotificationPolicy, NotificationGuard, NotificationServiceGuard};
pub use notification_template_auth::{NotificationTemplatePolicy, NotificationTemplateGuard, NotificationTemplateServiceGuard};

// <<< CUSTOM
// END CUSTOM
