//! NotificationTemplate API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the NotificationTemplate CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// NOTIFICATIONTEMPLATE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for NotificationTemplate
pub struct NotificationTemplateTestData;

impl TestDataGenerator for NotificationTemplateTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "event_type": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "channel": "whatsapp",
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "subject_template": null,
            "body_template": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "event_type": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "channel": "whatsapp",
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "subject_template": null,
            "body_template": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// NOTIFICATIONTEMPLATE API TEST
// ============================================================================

/// NotificationTemplate API test suite
pub struct NotificationTemplateApiTest {
    inner: GenericCrudTest<NotificationTemplateTestData>,
}

impl NotificationTemplateApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/notification_templates", "NotificationTemplate");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, NotificationTemplateTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for NotificationTemplateApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_notification_template_crud() {
        let mut test = NotificationTemplateApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add NotificationTemplate specific tests here
// <<< CUSTOM TESTS END >>>
