//! Notification API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Notification CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// NOTIFICATION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Notification
pub struct NotificationTestData;

impl TestDataGenerator for NotificationTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "event_id": Uuid::new_v4().to_string(),
            "event_type": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "template_id": null,
            "channel": "whatsapp",
            "recipient_party_id": null,
            "recipient_address": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "subject": null,
            "body": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "pending",
            "message_id": null,
            "failure_reason": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "event_id": Uuid::new_v4().to_string(),
            "event_type": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "template_id": null,
            "channel": "whatsapp",
            "recipient_party_id": null,
            "recipient_address": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "subject": null,
            "body": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "pending",
            "message_id": null,
            "failure_reason": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// NOTIFICATION API TEST
// ============================================================================

/// Notification API test suite
pub struct NotificationApiTest {
    inner: GenericCrudTest<NotificationTestData>,
}

impl NotificationApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/notifications", "Notification");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, NotificationTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for NotificationApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_notification_crud() {
        let mut test = NotificationApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Notification specific tests here
// <<< CUSTOM TESTS END >>>
