//! Notification Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::NotificationService;
use crate::application::service::NotificationTemplateService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// Notification service
    pub notification_service: Arc<NotificationService>,
    /// NotificationTemplate service
    pub notification_template_service: Arc<NotificationTemplateService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        notification_service: Arc<NotificationService>,
        notification_template_service: Arc<NotificationTemplateService>
    ) -> Self {
        Self {
            notification_service,
            notification_template_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::NotificationModule) -> Self {
        Self {
            notification_service: module.notification_service.clone(),
            notification_template_service: module.notification_template_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    notification_service: Option<Arc<NotificationService>>,
    notification_template_service: Option<Arc<NotificationTemplateService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the Notification service.
    pub fn with_notification_service(mut self, service: Arc<NotificationService>) -> Self {
        self.notification_service = Some(service);
        self
    }

    /// Set the NotificationTemplate service.
    pub fn with_notification_template_service(mut self, service: Arc<NotificationTemplateService>) -> Self {
        self.notification_template_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            notification_service: self.notification_service.expect("notification_service is required"),
            notification_template_service: self.notification_template_service.expect("notification_template_service is required"),
        }
    }
}
