//! Public events for Notification module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// NOTIFICATION EVENTS
// ============================================================================

/// Event published when a Notification is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationCreatedEvent {
    pub id: NotificationId,
    pub data: NotificationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Notification is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationUpdatedEvent {
    pub id: NotificationId,
    pub data: NotificationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Notification is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationDeletedEvent {
    pub id: NotificationId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// NOTIFICATIONTEMPLATE EVENTS
// ============================================================================

/// Event published when a NotificationTemplate is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationTemplateCreatedEvent {
    pub id: NotificationTemplateId,
    pub data: NotificationTemplateDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a NotificationTemplate is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationTemplateUpdatedEvent {
    pub id: NotificationTemplateId,
    pub data: NotificationTemplateDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a NotificationTemplate is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationTemplateDeletedEvent {
    pub id: NotificationTemplateId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Notification module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum NotificationEvent {
    NotificationCreated(NotificationCreatedEvent),
    NotificationUpdated(NotificationUpdatedEvent),
    NotificationDeleted(NotificationDeletedEvent),
    NotificationTemplateCreated(NotificationTemplateCreatedEvent),
    NotificationTemplateUpdated(NotificationTemplateUpdatedEvent),
    NotificationTemplateDeleted(NotificationTemplateDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for NotificationEventMetadata {
    fn default() -> Self {
        Self {
            module: "notification",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
