//! Notification Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Notification exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use notification::exports::{NotificationDto, NotificationQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `NotificationDto` - Data transfer object for Notification
/// - `NotificationSummary` - Summary view of Notification
/// - `NotificationId` - Type-safe ID wrapper
/// - `NotificationTemplateDto` - Data transfer object for NotificationTemplate
/// - `NotificationTemplateSummary` - Summary view of NotificationTemplate
/// - `NotificationTemplateId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `NotificationQueryService` - Read-only queries
///
/// ## Public Events
/// - `NotificationCreatedEvent` - Published when Notification is created
/// - `NotificationUpdatedEvent` - Published when Notification is updated
/// - `NotificationDeletedEvent` - Published when Notification is deleted
/// - `NotificationTemplateCreatedEvent` - Published when NotificationTemplate is created
/// - `NotificationTemplateUpdatedEvent` - Published when NotificationTemplate is updated
/// - `NotificationTemplateDeletedEvent` - Published when NotificationTemplate is deleted
pub struct ExportSummary;
