//! Public services for Notification module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Notification module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait NotificationQueryService: Send + Sync {
    /// Get Notification by ID
    async fn get_notification(&self, id: NotificationId) -> Result<Option<NotificationDto>>;

    /// Get Notification summary by ID
    async fn get_notification_summary(&self, id: NotificationId) -> Result<Option<NotificationSummary>>;

    /// Check if Notification exists
    async fn notification_exists(&self, id: NotificationId) -> Result<bool>;

    /// Get NotificationTemplate by ID
    async fn get_notification_template(&self, id: NotificationTemplateId) -> Result<Option<NotificationTemplateDto>>;

    /// Get NotificationTemplate summary by ID
    async fn get_notification_template_summary(&self, id: NotificationTemplateId) -> Result<Option<NotificationTemplateSummary>>;

    /// Check if NotificationTemplate exists
    async fn notification_template_exists(&self, id: NotificationTemplateId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of NotificationQueryService
pub struct NotificationQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> NotificationQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
