//! Public types for Notification module
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

// ============================================================================
// NOTIFICATION TYPES
// ============================================================================

/// Type-safe ID for Notification
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct NotificationId(pub Uuid);

impl NotificationId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for NotificationId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<NotificationId> for Uuid {
    fn from(id: NotificationId) -> Self {
        id.0
    }
}

/// Data transfer object for Notification
///
/// This is the public representation of Notification for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationDto {
    pub id: NotificationId,
    pub user_id: Uuid,
    pub notification_type: NotificationType,
    pub channel: NotificationChannel,
    pub title: String,
    pub body: String,
    pub image_url: Option<String>,
    pub action_url: Option<String>,
    pub action_type: Option<String>,
    pub reference_type: Option<String>,
    pub reference_id: Option<Uuid>,
    pub status: NotificationStatus,
    pub scheduled_at: Option<DateTime<Utc>>,
    pub sent_at: Option<DateTime<Utc>>,
    pub delivered_at: Option<DateTime<Utc>>,
    pub read_at: Option<DateTime<Utc>>,
    pub failed_at: Option<DateTime<Utc>>,
    pub failure_reason: Option<String>,
    pub retry_count: i32,
    pub external_id: Option<String>,
    pub priority: NotificationPriority,
    pub is_actionable: bool,
    pub action_taken: bool,
    pub action_taken_at: Option<DateTime<Utc>>,
    pub is_dismissed: bool,
    pub dismissed_at: Option<DateTime<Utc>>,
    pub metadata: serde_json::Value,
}

/// Summary view of Notification for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationSummary {
    pub id: NotificationId,
    pub title: String,
    pub status: NotificationStatus,
}

/// Reference to Notification for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationRef {
    pub id: NotificationId,
}

// ============================================================================
// NOTIFICATIONPREFERENCE TYPES
// ============================================================================

/// Type-safe ID for NotificationPreference
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct NotificationPreferenceId(pub Uuid);

impl NotificationPreferenceId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for NotificationPreferenceId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<NotificationPreferenceId> for Uuid {
    fn from(id: NotificationPreferenceId) -> Self {
        id.0
    }
}

/// Data transfer object for NotificationPreference
///
/// This is the public representation of NotificationPreference for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationPreferenceDto {
    pub id: NotificationPreferenceId,
    pub user_id: Uuid,
    pub channel: NotificationChannel,
    pub category: NotificationCategory,
    pub status: PreferenceStatus,
    pub is_enabled: bool,
    pub quiet_hours_enabled: bool,
    pub quiet_start: Option<String>,
    pub quiet_end: Option<String>,
    pub frequency: Option<String>,
    pub max_per_day: Option<i32>,
    pub data: serde_json::Value,
}

/// Summary view of NotificationPreference for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationPreferenceSummary {
    pub id: NotificationPreferenceId,
    pub status: PreferenceStatus,
}

/// Reference to NotificationPreference for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationPreferenceRef {
    pub id: NotificationPreferenceId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
