//! Public types for Notification module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use crate::domain::entity::*;

// ============================================================================
// NOTIFICATION TYPES
// ============================================================================

/// Type-safe ID for Notification
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct NotificationId(pub Uuid);

impl NotificationId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for NotificationId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<NotificationId> for Uuid {
    fn from(id: NotificationId) -> Self {
        id.0
    }
}

/// Data transfer object for Notification
///
/// This is the public representation of Notification for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationDto {
    pub id: NotificationId,
    pub company_id: Uuid,
    pub event_id: Uuid,
    pub event_type: String,
    pub template_id: Option<Uuid>,
    pub channel: NotifChannel,
    pub recipient_party_id: Option<Uuid>,
    pub recipient_address: String,
    pub subject: Option<String>,
    pub body: String,
    pub status: NotificationStatus,
    pub message_id: Option<Uuid>,
    pub failure_reason: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of Notification for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationSummary {
    pub id: NotificationId,
    pub status: NotificationStatus,
}

/// Reference to Notification for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationRef {
    pub id: NotificationId,
}

// ============================================================================
// NOTIFICATIONTEMPLATE TYPES
// ============================================================================

/// Type-safe ID for NotificationTemplate
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct NotificationTemplateId(pub Uuid);

impl NotificationTemplateId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for NotificationTemplateId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<NotificationTemplateId> for Uuid {
    fn from(id: NotificationTemplateId) -> Self {
        id.0
    }
}

/// Data transfer object for NotificationTemplate
///
/// This is the public representation of NotificationTemplate for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationTemplateDto {
    pub id: NotificationTemplateId,
    pub company_id: Uuid,
    pub event_type: String,
    pub channel: NotifChannel,
    pub name: String,
    pub subject_template: Option<String>,
    pub body_template: String,
    pub is_active: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of NotificationTemplate for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationTemplateSummary {
    pub id: NotificationTemplateId,
    pub name: String,
}

/// Reference to NotificationTemplate for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NotificationTemplateRef {
    pub id: NotificationTemplateId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
