//! Notification Module
//!
//! Generated by backbone-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::NotificationService;
pub use application::service::NotificationPreferenceService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Notification module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let notification = NotificationModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// let router = notification.routes();
/// ```
pub struct NotificationModule {
    pub notification_service: Arc<NotificationService>,
    pub notification_preference_service: Arc<NotificationPreferenceService>,
}

impl NotificationModule {
    /// Create a new module builder
    pub fn builder() -> NotificationModuleBuilder {
        NotificationModuleBuilder::new()
    }

    /// Configure HTTP routes for this module using Axum
    ///
    /// Returns an Axum Router with all 12 Backbone CRUD endpoints per entity.
    pub fn routes(&self) -> Router {
        use presentation::http::{
            create_notification_routes,
            create_notification_preference_routes,
        };

        Router::new()
            .merge(create_notification_routes(self.notification_service.clone()))
            .merge(create_notification_preference_routes(self.notification_preference_service.clone()))
    }
}

/// Builder for NotificationModule
pub struct NotificationModuleBuilder {
    db_pool: Option<PgPool>,
}

impl NotificationModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<NotificationModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Notification service
        let notification_repository = Arc::new(NotificationRepository::new(db_pool.clone()));
        let notification_service = Arc::new(NotificationService::with_repository(notification_repository.clone()));

        // NotificationPreference service
        let notification_preference_repository = Arc::new(NotificationPreferenceRepository::new(db_pool.clone()));
        let notification_preference_service = Arc::new(NotificationPreferenceService::with_repository(notification_preference_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(NotificationModule {
            notification_service,
            notification_preference_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for NotificationModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
