//! Notification Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::NotificationService;
pub use application::service::NotificationTemplateService;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Notification module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let notification = NotificationModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = notification.all_crud_routes();
/// ```
pub struct NotificationModule {
    pub(crate) notification_service: Arc<NotificationService>,
    pub(crate) notification_template_service: Arc<NotificationTemplateService>,
    // <<< CUSTOM FIELDS
    /// The validated write engine — idempotent fan-out, template render, dispatch through
    /// `CommunicationPort`. This delivers the module's stated purpose; the two CRUD services
    /// above are convenience scaffolding (see `readonly_routes` / `guarded_routes`).
    pub(crate) write_service: Arc<application::service::NotificationWriteService>,
    // END CUSTOM
}

impl NotificationModule {
    /// Create a new module builder
    pub fn builder() -> NotificationModuleBuilder {
        NotificationModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_notification_routes,
            create_notification_template_routes,
        };

        Router::new()
            .merge(create_notification_routes(self.notification_service.clone()))
            .merge(create_notification_template_routes(self.notification_template_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD; prefer readonly_routes() + validated writes, or all_crud_routes() for the full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }

    /// Read-only routes for every entity (GET endpoints only) — the safe base.
    ///
    /// Generic mutation can't reach here, so this surface cannot bypass a
    /// validated write service's invariants. Use this as the production base and
    /// merge validated write routes (or a write service's HTTP layer) onto it.
    pub fn readonly_routes(&self) -> Router {
        use presentation::http::{
            create_notification_read_routes,
            create_notification_template_read_routes,
        };

        Router::new()
            .merge(create_notification_read_routes(self.notification_service.clone()))
            .merge(create_notification_template_read_routes(self.notification_template_service.clone()))
    }

    // <<< CUSTOM METHODS
    /// The validated notification engine (idempotent fan-out → render → dispatch).
    ///
    /// A composing service drives this from its domain-event subscriptions, passing a
    /// `CommunicationPort` impl over backbone-communication. Generic CRUD on a `Notification`
    /// row bypasses the dedup invariant — use THIS, not the write routes.
    pub fn write_service(&self) -> Arc<application::service::NotificationWriteService> {
        self.write_service.clone()
    }

    /// The recommended production surface: `Notification` **read-only** (a Notification is a
    /// derived, append-only record — never hand-created) + `NotificationTemplate` full CRUD
    /// (a template IS master data). `Notification` writes go through [`Self::write_service`]
    /// only. `all_crud_routes()` exposes unguarded writes and is for trusted/admin/seeding.
    pub fn guarded_routes(&self) -> Router {
        use presentation::http::{
            create_notification_read_routes,
            create_notification_template_routes,
        };

        Router::new()
            .merge(create_notification_read_routes(self.notification_service.clone()))
            .merge(create_notification_template_routes(self.notification_template_service.clone()))
    }
    // END CUSTOM
}

/// Builder for NotificationModule
pub struct NotificationModuleBuilder {
    db_pool: Option<PgPool>,
}

impl NotificationModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<NotificationModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Notification service
        let notification_repository = Arc::new(NotificationRepository::new(db_pool.clone()));
        let notification_service = Arc::new(NotificationService::with_repository(notification_repository.clone()));

        // NotificationTemplate service
        let notification_template_repository = Arc::new(NotificationTemplateRepository::new(db_pool.clone()));
        let notification_template_service = Arc::new(NotificationTemplateService::with_repository(notification_template_repository.clone()));

        // <<< CUSTOM
        // The validated write engine. Self-constructs from the pool; CommunicationPort and
        // NotificationEventSink stay per-call (the composing service's concern). Construction
        // asserts both entities expose company_field() so the tenant fence is wired (see new()).
        let write_service = Arc::new(application::service::NotificationWriteService::new(db_pool.clone()));
        // END CUSTOM

        Ok(NotificationModule {
            notification_service,
            notification_template_service,
            // <<< CUSTOM
            write_service,
            // END CUSTOM
        })
    }
}

impl Default for NotificationModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
