//! Application use cases
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod notification_usecases;
pub mod notification_preference_usecases;

pub use notification_usecases::{
    CreateNotificationUseCase, UpdateNotificationUseCase, GetNotificationUseCase,
    DeleteNotificationUseCase, ListNotificationUseCase,
};
pub use notification_preference_usecases::{
    CreateNotificationPreferenceUseCase, UpdateNotificationPreferenceUseCase, GetNotificationPreferenceUseCase,
    DeleteNotificationPreferenceUseCase, ListNotificationPreferenceUseCase,
};

// <<< CUSTOM
// END CUSTOM
