//! HTTP handlers
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod notification_handler;
pub mod notification_template_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use notification_handler::{create_notification_routes, create_notification_read_routes, create_notification_write_routes};
pub use notification_template_handler::{create_notification_template_routes, create_notification_template_read_routes, create_notification_template_write_routes};
// <<< CUSTOM
// END CUSTOM
