//! HTTP handlers
//!
//! Auto-generated by backbone-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod notification_handler;
pub mod notification_preference_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use notification_handler::create_notification_routes;
pub use notification_preference_handler::create_notification_preference_routes;
// <<< CUSTOM
// END CUSTOM
