//! Event subscriptions for Notification module
//!
//! Event subscriptions handle domain events from other modules.
//! They implement the EventHandler trait for incoming events.
//!
//! Generated by backbone-schema. Custom code sections are preserved.

// Event subscriptions will be generated here by backbone-schema
// Use: backbone schema generate notification --target event-subscription
